version: '3.8'
services:
    #restart: always
  app:
    build:
        context: .
        dockerfile: Dockerfile
    ports:
      - "80:80"

  app_redis:
    image: redis:latest
    hostname: redis
    container_name: app_redis
    command:
      - 'redis-server'
    ports:
      - "6379:6379"